[package]
name = "reference"
version = "0.1.0"
edition = "2021"

[dependencies]
arbitrary = "1.3.2"
patterns = { path = ".." }

[dev-dependencies]
aligned-vec = "0.6.1"
criterion = "0.5.1"
xxhash-rust = { version = "0.8.6", features = ["xxh3"] }
